### PR TITLE
[WIP] Add support for Latin dicts

### PR DESCRIPTION
**Pull request by ymarco**
Of the format used in https://nikita-moor.github.io/dictionaries/dictionaries.html .
Currently only Lewis 1890 was tested, I'm planning to add a
Latin-English one as well

### CODE REVIEW

**Comment by ymarco** [comment]
In the last commit, the following dictionaries are supported:
```
 | Dictionary's name                              | type          | Word count |
 |------------------------------------------------+---------------+------------|
 | Index verbōrum, Appleton (1914)                | latin latin   |       2183 |
 | An Elementary Latin Dictionary, Lewis (1890)   | latin english |      17582 |
 | Hand-book of Latin Synonymes, Döderlein (1875) | latin english |        556 |
 | A Latin Dictionary, Lewis & Short (1879)       | latin english |      51596 |
 | Glossarium Anglico-Latinum, Redmond (2005)     | english latin |      10867 |
```

**Comment by ymarco** [comment]
The last commits converted from regex-based parsing to using libxml, which is much cleaner

**Comment by tecosaur** [comment]
Ready yet? :stuck_out_tongue:

**Comment by ymarco** [comment]
I've been using it for a while without any issues. I'll take a last look
at the code in a few days to see if it needs any cleaning, but
otherwise, yes!

**Comment by tecosaur** [comment]
Lovely!

**Comment by tecosaur** [comment]
:eyes:

**Comment by ymarco** [comment]
I'm yet to do the IDs we talked about. In a few days.

**Comment by tecosaur** [comment]
NP, I just assume other people are as bad as I am when it comes to these things.
Also, I'd rather not introduce a merge conflict if `master` develops too much.

**Comment by tecosaur** [comment]
Oops, sorry. I just wanted to shut up the byte-compiler.

It's just shunting all the `defvar` blocks to the start of the file, so it shouldn't be too bad though.

**Comment by HanshenWang** [comment]
Looking forwards to this feature!

**Comment by ymarco** [comment]
tecosaur and I decided to not merge this.

My code basically parses HTML to an Emacs buffer according to CSS rules that I hard-coded manually. It works in the general case, but there are many edge cases (where the result is still usable mind you) that I'm not willing to code.

So, we decided to keep it on my branch, to avoid being responsible for all these minor things. You're free to try it yourself, but it won't get anywhere official. That's it.

**Pull request closed without merging**
